project:
  type: website
  output-dir: docs
  resources: styles.css

website:
  title: "<img src='image/logo1.png' style='height:40px;'>"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - section5.qmd

format:
  html:
    theme: zephyr
    mainfont: arial
    fontsize: 1rem
    linkcolor: "#C8102E"
    css: styles.css
    toc: true